# Generated by Django 4.0.1 on 2022-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskai',
            name='diena',
            field=models.DateField(),
        ),
    ]
