# Generated by Django 4.0.1 on 2022-01-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_taskai_diena'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskai',
            name='arbata',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
