# Generated by Django 4.0.1 on 2022-01-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_taskai_arbata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskai',
            name='km',
            field=models.IntegerField(),
        ),
    ]
