# Generated by Django 4.0.1 on 2022-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_taskai_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskai',
            name='pristatymai',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskai',
            name='uzsakymai',
            field=models.IntegerField(),
        ),
    ]
