# Generated by Django 4.0.1 on 2022-01-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_taskai_pristatymai_alter_taskai_uzsakymai'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskai',
            name='pristatymai_pakuotes',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskai',
            name='uzsakymai_pakuotes',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
