# Generated by Django 4.0.1 on 2022-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_taskai_pristatymai_pakuotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskai',
            name='nepavyko',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskai',
            name='arbata',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskai',
            name='pristatymai_pakuotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskai',
            name='uzsakymai_pakuotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
