# Generated by Django 4.0.1 on 2022-02-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_taskai_nepavyko_alter_taskai_arbata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskai',
            name='pastomatai',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
